In [2]:
import pandas as pd
import string
from nltk.corpus import stopwords
from nltk import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
import streamlit as st

# Download the raw data from Yelp

URL: https://www.yelp.com/dataset/download
        
The total file size is 4GB.

# Import raw data (json) and convert into CSV

It takes 5 minutes to run

In [10]:
# import json

# def conv_json_to_csv(inFile, outFile):
#     with open(inFile) as f:
#         data = []
#         for line in f:
#             if line.strip():  # Check if the line is not empty
#                 obj = json.loads(line)
#                 data.append(obj)

#     # Open the CSV file in write mode
#     with open(outFile, 'w', newline='') as file:
#         fieldnames = data[0].keys()
#         writer = csv.DictWriter(file, fieldnames=fieldnames)

#         # Write the header row
#         writer.writeheader()

#         # Write the data rows
#         writer.writerows(data)
        
# conv_json_to_csv('raw_data/yelp_academic_dataset_review.json', 'notebooks/csv/yelp_review.csv')
# conv_json_to_csv('raw_data/yelp_academic_dataset_business.json', 'notebooks/csv/yelp_business.csv')

# Create the Review Dataframes - df_review_top10

In [3]:
df_business = pd.read_csv('notebooks/csv/yelp_business.csv')

In [4]:
# CSV file from Sophia
df_review = pd.read_csv('notebooks/csv/new_orleans_reviews.csv')

In [5]:
# CSV files from Rene
df_rene = pd.read_csv('notebooks/csv/avg_stars10m_radius.csv')

In [6]:
# CSV files from Sandun
df_praise_top10 = pd.read_csv('notebooks/csv/res_top5_compliments.csv')
df_complaint_top10 = pd.read_csv('notebooks/csv/res_top5_complaints.csv')

# Convert the Data Type

## Date to be Datetime

In [9]:
df_review['date'].dtype

dtype('O')

In [13]:
df_review['date'] = pd.to_datetime(df_review['date'], format='%Y-%m-%d')
df_review['date'].dtype

dtype('<M8[ns]')

# Combine the 4 Tables into 1

## Combine df_business & df_rene

In [15]:
df_business = df_business[['business_id', 'stars','name','review_count','categories']]
df_business.head(2)

,business_id,stars,name,review_count,categories
0,Pns2l4eNsfO8kk83dixA6A,5.0,"Abby Rappoport, LAC, CMQ",7,"Doctors, Traditional Chinese Medicine, Naturop..."
1,mpf3x-BjTdTEA3yCZrAYPw,3.0,The UPS Store,15,"Shipping Centers, Local Services, Notaries, Ma..."

In [16]:
df_rene = df_rene[["business_id","avg_stars10m_radius"]]
df_rene.head(2)

              business_id  avg_stars10m_radius
0  -0TffRSXXIlBYVbb5AwfTg             4.016129
1  -FM4CxOg4XXmX_Ebky_SiQ             4.192308

In [17]:
df_business = pd.merge(df_business, df_rene, on='business_id', how='inner')
df_business.head(2)

,business_id,stars,name,review_count,categories,avg_stars10m_radius
0,SZU9c8V2GuREDN5KgyHFJw,4.0,Santa Barbara Shellfish Company,2404,"Live/Raw Food, Restaurants, Seafood, Beer Bar,...",4.192308
1,ORL4JE6tz3rJxVqkdKfegA,3.0,Gaylord Opryland Resort & Convention Center,1639,"Venues & Event Spaces, Performing Arts, Arts &...",4.166667

## Combine df_review & df_business

In [18]:
df_review = pd.merge(df_review, df_business, on='business_id', how='inner')
df_review = df_review.rename(columns={'stars_x': 'stars'})
df_review = df_review.rename(columns={'stars_y': 'restaurant_avg_star'})
df_review.head(2)

,review_id,user_id,business_id,stars,useful,funny,cool,text,date,restaurant_avg_star,name,review_count,categories,avg_stars10m_radius
0,z0osLHDvXvzfm57D4DmD2Q,xVKE_HJ2pwUtTdLbL3pnCg,S2Ho8yLxhKAa26pBAm6rxA,3.0,0,0,0,"Service was crappy, and food was mediocre. I ...",2016-11-22,4.0,Creole House Restaurant & Oyster Bar,1594,"Cajun/Creole, Seafood, Restaurants, Breakfast ...",4.05814
1,tXHWJWnTdrraHGUqaPWj3g,zKAHSNzqvwsyoFCw3QpafA,S2Ho8yLxhKAa26pBAm6rxA,4.0,0,0,0,Enjoyed my fish out at a sidewalk table. A bi...,2018-05-19,4.0,Creole House Restaurant & Oyster Bar,1594,"Cajun/Creole, Seafood, Restaurants, Breakfast ...",4.05814

In [19]:
df_review = df_review[['review_id','business_id', 'stars','name','text','restaurant_avg_star','review_count','avg_stars10m_radius','date']]
df_review.head(2)

,review_id,business_id,stars,name,text,restaurant_avg_star,review_count,avg_stars10m_radius,date
0,z0osLHDvXvzfm57D4DmD2Q,S2Ho8yLxhKAa26pBAm6rxA,3.0,Creole House Restaurant & Oyster Bar,"Service was crappy, and food was mediocre. I ...",4.0,1594,4.05814,2016-11-22
1,tXHWJWnTdrraHGUqaPWj3g,S2Ho8yLxhKAa26pBAm6rxA,4.0,Creole House Restaurant & Oyster Bar,Enjoyed my fish out at a sidewalk table. A bi...,4.0,1594,4.05814,2018-05-19

## Combine df_review and df_praise

In [20]:
df_praise_top10.head(2)

    Unnamed: 0  normalized_score             business_id
0  best oyster          2.414669  GBTPC53ZrG1ZBY3DT8Mbcw
1     savannah          2.385819  GBTPC53ZrG1ZBY3DT8Mbcw

In [21]:
df_complaint_top10.head(2)

  Unnamed: 0  normalized_score             business_id
0       poor          0.519310  GBTPC53ZrG1ZBY3DT8Mbcw
1  customers          0.377411  GBTPC53ZrG1ZBY3DT8Mbcw

In [22]:
df_praise_top10 = pd.merge(df_praise_top10,df_business[['business_id', 'name']], on='business_id', how='inner')
df_praise_top10.head(2)

    Unnamed: 0  normalized_score             business_id  name
0  best oyster          2.414669  GBTPC53ZrG1ZBY3DT8Mbcw  Luke
1     savannah          2.385819  GBTPC53ZrG1ZBY3DT8Mbcw  Luke

In [23]:
df_complaint_top10 = pd.merge(df_complaint_top10,df_business[['business_id', 'name']], on='business_id', how='inner')
df_complaint_top10.head(2)

  Unnamed: 0  normalized_score             business_id  name
0       poor          0.519310  GBTPC53ZrG1ZBY3DT8Mbcw  Luke
1  customers          0.377411  GBTPC53ZrG1ZBY3DT8Mbcw  Luke

In [26]:
df_praise_top10 = df_praise_top10.rename(columns={'Unnamed: 0': 'praise_text'})
df_praise_top10 = df_praise_top10.rename(columns={'normalized_score': 'praise_score'})
df_praise_top10.head(3)

       praise_text  praise_score             business_id  name
0      best oyster      2.414669  GBTPC53ZrG1ZBY3DT8Mbcw  Luke
1         savannah      2.385819  GBTPC53ZrG1ZBY3DT8Mbcw  Luke
2  sprouts amazing      2.353093  GBTPC53ZrG1ZBY3DT8Mbcw  Luke

In [27]:
df_complaint_top10 = df_complaint_top10.rename(columns={'Unnamed: 0': 'complaint_text'})
df_complaint_top10 = df_complaint_top10.rename(columns={'normalized_score': 'complaint_score'})
df_complaint_top10.head(3)

  complaint_text  complaint_score             business_id  name
0           poor         0.519310  GBTPC53ZrG1ZBY3DT8Mbcw  Luke
1      customers         0.377411  GBTPC53ZrG1ZBY3DT8Mbcw  Luke
2       terrible         0.295643  GBTPC53ZrG1ZBY3DT8Mbcw  Luke

# Pick Top 10 Restaurants

## df_review_top10

In [28]:
review_counts = df_review['business_id'].value_counts().reset_index(name='review_count')
review_counts.columns = ['business_id', 'review_count']

top_10_business_ids = review_counts.head(10)['business_id']

df_review_top10 = df_review[df_review['business_id'].isin(top_10_business_ids)]

df_review_top10.shape

(52968, 9)

In [29]:
df_review_top10.head(2)

,review_id,business_id,stars,name,text,restaurant_avg_star,review_count,avg_stars10m_radius,date
7987,yyrMqY7sNp5gT7KJ1AaYWA,GBTPC53ZrG1ZBY3DT8Mbcw,4.0,Luke,We have been here twice for brunch and have en...,4.0,4554,4.05814,2016-03-07
7988,wEfzqOfbwn4Ohe2ZDOLAzw,GBTPC53ZrG1ZBY3DT8Mbcw,4.0,Luke,First meal in New Orleans. I had the $15 lunch...,4.0,4554,4.05814,2012-11-06

In [30]:
top10_restaurants = df_review_top10['name'].unique()
top10_restaurants

array(['Luke', 'Gumbo Shop', "Commander's Palace", 'Royal House',
       "Felix's Restaurant & Oyster Bar", 'Cochon', "Mother's Restaurant",
       'Oceana Grill', 'Acme Oyster House', 'Ruby Slipper - New Orleans'],
      dtype=object)

## df_business_top10

In [31]:
df_business_top10 = df_business[df_business['name'].isin(top10_restaurants)]
df_business_top10.head(10)

,business_id,stars,name,review_count,categories,avg_stars10m_radius
11,GBTPC53ZrG1ZBY3DT8Mbcw,4.0,Luke,4554,"German, Restaurants, Seafood, Cocktail Bars, F...",4.05814
73,VQcCL9PiNL_wkGf-uF3fjg,4.0,Royal House,5070,"American (New), Restaurants, Sandwiches, Seafo...",4.05814
75,_C7QiQQc47AOEv4PE3Kong,4.5,Commander's Palace,4876,"French, Restaurants, Cocktail Bars, Nightlife,...",4.05814
96,qb28j-FNX1_6xm7u372TZA,4.0,Gumbo Shop,3902,"Cajun/Creole, Seafood, Restaurants",4.05814
130,VaO-VW3e1kARkU9bP1E7Fw,4.0,Felix's Restaurant & Oyster Bar,3966,"Restaurants, Sandwiches, Seafood, Cajun/Creole",4.05814
182,6a4gLLFSgr-Q6CZXDLzBGQ,4.0,Cochon,4421,"Cajun/Creole, Seafood, Restaurants",4.05814
187,iSRTaT9WngzB8JJ2YKJUig,3.5,Mother's Restaurant,5185,"Cajun/Creole, Restaurants, Event Planning & Se...",4.05814
215,ac1AeYqs8Z4_e2X5M3if2A,4.0,Oceana Grill,7400,"Restaurants, Seafood, Cajun/Creole, Breakfast ...",4.05814
218,_ab50qdWOk0DdB6XOrBitw,4.0,Acme Oyster House,7568,"Live/Raw Food, Seafood, Restaurants, Cajun/Creole",4.05814
294,oBNrLz4EDhiscSlbOl8uAw,4.5,Ruby Slipper - New Orleans,5193,"Restaurants, American (Traditional), American ...",4.05814

# Preprocess - Clean Text

In [32]:
def remove_punctuation(text):
    return "".join(char for char in text if not char in string.punctuation)
preprocessed_stopwords= [remove_punctuation(word) for word in stopwords.words('english')]

def preprocessing(sentence):
    # remove whitespace
    t1 = sentence.strip()
    # lowercase characters
    t2 = t1.lower()
    # remove numbers
    
    t3 = ''.join(char for char in t2 if not char.isdigit())
    # remove punctuation
    t4 = "".join(char for char in t3 if not char in string.punctuation)
    # tokenize
    tokens = t4.split(" ")
    # lemmatize
    stopwords_removed = [
        word for word in tokens if word not in preprocessed_stopwords
    ]
    return " ".join(stopwords_removed)

# Clean reviews
df_review_top10['clean_text'] = df_review_top10['text'].apply(preprocessing)

/var/folders/_n/cr9xqtgn70g_tclcyk9hd0nw0000gn/T/ipykernel_18935/3519110220.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_review_top10['clean_text'] = df_review_top10['text'].apply(preprocessing)

In [33]:
df_review_top10.head(2)

,review_id,business_id,stars,name,text,restaurant_avg_star,review_count,avg_stars10m_radius,date,clean_text
7987,yyrMqY7sNp5gT7KJ1AaYWA,GBTPC53ZrG1ZBY3DT8Mbcw,4.0,Luke,We have been here twice for brunch and have en...,4.0,4554,4.05814,2016-03-07,twice brunch enjoyed immensely everything trie...
7988,wEfzqOfbwn4Ohe2ZDOLAzw,GBTPC53ZrG1ZBY3DT8Mbcw,4.0,Luke,First meal in New Orleans. I had the $15 lunch...,4.0,4554,4.05814,2012-11-06,first meal new orleans lunch special seafood ...

# Export dataframes to CSV

In [35]:
df_review_top10.to_csv('notebooks/csv/df_review_top10.csv', index=False)

In [36]:
df_business_top10.to_csv('notebooks/csv/df_business_top10.csv', index=False)

In [37]:
df_praise_top10.to_csv('notebooks/csv/df_praise_top10.csv', index=False)

In [38]:
df_complaint_top10.to_csv('notebooks/csv/df_complaint_top10.csv', index=False)

# Preprocess - Vectorize

This cannot run

In [ ]:
# vectorizer = TfidfVectorizer(ngram_range=(1,3))
# vectorized_text = vectorizer.fit_transform(df_review_top10['clean_text'])
# vectorized_text = pd.DataFrame(
#     vectorized_text.toarray(),
#     columns = vectorizer.get_feature_names_out()
# )

# df_example

In [3]:
df_example = pd.read_csv('https://storage.googleapis.com/yelp_review_nlp/df_example_top10.csv')

In [6]:
df_example = df_example.drop(['name.1', 'business_id.1'], axis=1)

In [7]:
df_example.rename()

,business_id,name,complaint_words,clean_text,complaint_stars,praise_words,praise_sample_reviews,praise_stars
0,GBTPC53ZrG1ZBY3DT8Mbcw,Luke,poor,let start saying oysters wonderful rest meal ...,2,best oyster,went happy hour raw oysters heaven perfectio...,5
1,GBTPC53ZrG1ZBY3DT8Mbcw,Luke,customers,travel quite bit let say amazing customer serv...,5,savannah,suffering luke withdrawal since last trip jazz...,5
2,GBTPC53ZrG1ZBY3DT8Mbcw,Luke,terrible,place sucks terrible service overpriced medioc...,1,sprouts amazing,reservations two seated right away within two...,2
3,GBTPC53ZrG1ZBY3DT8Mbcw,Luke,second,second choice finding rio mar closed mardi gra...,5,richie rich,restaurant star food service went bachelorett...,5
4,GBTPC53ZrG1ZBY3DT8Mbcw,Luke,open,place hip perhaps hip many tolerate boistero...,4,tristan,stumbled upon lukes way alabama via nola firs...,4
5,qb28j-FNX1_6xm7u372TZA,Gumbo Shop,mushy,thing worth chicken andouille gumbo family mem...,2,tim,first restaurant ever went first visit nola s...,5
6,qb28j-FNX1_6xm7u372TZA,Gumbo Shop,frozen,awful simply awful completely embarrassed poor...,1,everyday,bread pudding come get bread pudding probabl...,5
7,qb28j-FNX1_6xm7u372TZA,Gumbo Shop,waste,came highly recommended close friend come arou...,1,soooooo,everyday nola multiple occasions even bought c...,5
8,qb28j-FNX1_6xm7u372TZA,Gumbo Shop,awful,awful simply awful completely embarrassed poor...,1,boudin creole,little lot things chicken okra gumbo louisiana...,5
9,qb28j-FNX1_6xm7u372TZA,Gumbo Shop,trap,tourist trap yes give stars atmosphere food...,2,boudin creole mustard,little lot things chicken okra gumbo louisiana...,5
10,_C7QiQQc47AOEv4PE3Kong,Commander's Palace,shorts,yes want eat here\nif want great old southern ...,5,years come,service impeccable food talking years come fav...,5
11,_C7QiQQc47AOEv4PE3Kong,Commander's Palace,wearing,great service well done food little hyped uppr...,4,place especially,whenever travel received suggestions friends c...,5
12,_C7QiQQc47AOEv4PE3Kong,Commander's Palace,rude,would give place quite somewhat better ive ...,4,fourth,always wanted visit commanders palace finally...,5
13,_C7QiQQc47AOEv4PE3Kong,Commander's Palace,terrible,start saying food amazing desserts bwst part ...,3,amazing service impeccable,came large group party food amazing service im...,5
14,_C7QiQQc47AOEv4PE3Kong,Commander's Palace,dressed,second visit commanders palace enjoy dining re...,5,orleans one best,commanders palace largely considered best rest...,5
15,VQcCL9PiNL_wkGf-uF3fjg,Royal House,disgusting,disgusting food came cold shrimps still poop v...,1,best servers,chose place anniversary dinner boyfriend sunda...,5
16,VQcCL9PiNL_wkGf-uF3fjg,Royal House,burnt,royal house nice hidden gem new orleans aptly ...,4,melva server,service melva server bubbly sweet loves job kn...,5
17,VQcCL9PiNL_wkGf-uF3fjg,Royal House,worst service,restaurant worst service restaurant ever nola ...,1,dream,came due fellow yelpers wanted try alligator n...,4
18,VQcCL9PiNL_wkGf-uF3fjg,Royal House,time money,first arrive get seated balcony everything le...,1,importantly,one word becks best bartender ever know alcoho...,5
19,VQcCL9PiNL_wkGf-uF3fjg,Royal House,service horrible,used love restaurant got new chef everything c...,1,leroy,came large group around saturday seated immed...,5
20,VaO-VW3e1kARkU9bP1E7Fw,Felix's Restaurant & Oyster Bar,disgusting,im giving stars oysters plump pretty good sa...,2,yvette,ended felixs meeting locals asking oyster reco...,5
21,VaO-VW3e1kARkU9bP1E7Fw,Felix's Restaurant & Oyster Bar,awful,awful overpriced food jambalaya resembled uncl...,1,way better acme,one best meals ive new orleans way better acme...,5
22,VaO-VW3e1kARkU9bP1E7Fw,Felix's Restaurant & Oyster Bar,bill,consistently great service great food never wa...,5,get charbroiled,ever new orleans must go felixs best oysters i...,5
23,VaO-VW3e1kARkU9bP1E7Fw,Felix's Restaurant & Oyster Bar,dirty,kind divey spot food oysters ok kind dirty gue...,2,sat oyster,best oyster new orleans husband sat oyster bar...,5
24,VaO-VW3e1kARkU9bP1E7Fw,Felix's Restaurant & Oyster Bar,empty,sit bar want quicker service \n\nthey pretty ...,3,wait line across,great food great service great location grill...,5
25,6a4gLLFSgr-Q6CZXDLzBGQ,Cochon,terrible,great food terrible service get seated rese...,3,rocks,place rocks asked concierge westin best local...,5
26,6a4gLLFSgr-Q6CZXDLzBGQ,Cochon,worst,nochon hype substance first service sucks gi...,1,oysters die,awesome fantastic staff great atmosphere crawf...,5
27,6a4gLLFSgr-Q6CZXDLzBGQ,Cochon,hostess,sis fabulous dinner cochon wow started w fri...,5,amazing mac,omg begin food amazing mac cheese alligator gu...,5
28,6a4gLLFSgr-Q6CZXDLzBGQ,Cochon,salty,get people come food salty uninspired servers ...,1,go nola,absolutely delicious alligator amazing even th...,5
29,6a4gLLFSgr-Q6CZXDLzBGQ,Cochon,rude,get people come food salty uninspired servers ...,1,amazing oysters,amazing oysters crocodile delicious broccoli s...,5
30,iSRTaT9WngzB8JJ2YKJUig,Mother's Restaurant,place dirty,place dirty rude flavor cold food disappoi...,1,boy delicious,waited line outside lunch glad someone told us...,5
31,iSRTaT9WngzB8JJ2YKJUig,Mother's Restaurant,rude service,absolutely trash avoid place \n rude service\n...,1,best poboy,incredible food ferdi special best poboy new o...,5
32,iSRTaT9WngzB8JJ2YKJUig,Mother's Restaurant,filthy,hear place always long line people even waitin...,1,fried chicken worth,based recommendation friend looking forward tr...,3
33,iSRTaT9WngzB8JJ2YKJUig,Mother's Restaurant,disgusting,place dirty rude flavor cold food disappoi...,1,chicken worth,based recommendation friend looking forward tr...,3
34,iSRTaT9WngzB8JJ2YKJUig,Mother's Restaurant,worse,chifoodie nolatourism foodtourism blackownedbu...,2,authentic cajun,im sitting mardi gras weekend new orleans no...,4
35,ac1AeYqs8Z4_e2X5M3if2A,Oceana Grill,poisoning,worst meal ive ever served anywhere ever\n\ni ...,1,service errol,nola days ate breakfast twice service errol ...,5
36,ac1AeYqs8Z4_e2X5M3if2A,Oceana Grill,disgusting,food hear okay seafood came bit warm sitting h...,3,amazing new orleans,oh goodness even know start incredible restaur...,5
37,ac1AeYqs8Z4_e2X5M3if2A,Oceana Grill,food poisoning,worst meal ive ever served anywhere ever\n\ni ...,1,amazing new,oh goodness even know start incredible restaur...,5
38,ac1AeYqs8Z4_e2X5M3if2A,Oceana Grill,sick,friend new orleans days went twice thats good...,5,best waiter,first night ran mardi gras parade krewe du vie...,4
39,ac1AeYqs8Z4_e2X5M3if2A,Oceana Grill,nightmares,finally decided write review watching episode ...,4,omg good,yesterday marks rd time dine times amazing se...,5
40,_ab50qdWOk0DdB6XOrBitw,Acme Oyster House,waste,yes acme charbroiled oysters came table bubbl...,2,line scare,new orleans week eat every day many times alwa...,5
41,_ab50qdWOk0DdB6XOrBitw,Acme Oyster House,poor,many acme locations many occasions sampled muc...,5,orleans oyster,food good restaurant visit every time im new o...,5
42,_ab50qdWOk0DdB6XOrBitw,Acme Oyster House,manager,party po boy served cent bread chargrilled ...,1,new orleans oyster,food good restaurant visit every time im new o...,5
43,_ab50qdWOk0DdB6XOrBitw,Acme Oyster House,horrible,place good ok oysters good place town real con...,2,changed life,absolutely amazing food boo fries changed life,5
44,_ab50qdWOk0DdB6XOrBitw,Acme Oyster House,business,trips nola past months ive managed eat acme o...,5,hands best oysters,hands best oysters ever charbroiled oysters se...,5
45,oBNrLz4EDhiscSlbOl8uAw,Ruby Slipper - New Orleans,terrible,came rainy saturday morning breakfast group g...,4,server freddie awesome,awesome eggs benedict bloody marys fast friend...,5
46,oBNrLz4EDhiscSlbOl8uAw,Ruby Slipper - New Orleans,horrible,hopping loud bustling joint late saturday morn...,4,freddie great server,food great easily accommodated group try corn...,5
47,oBNrLz4EDhiscSlbOl8uAw,Ruby Slipper - New Orleans,worst,sucks worst biscuits ever extremely pricey poo...,1,service freddie,great food awesome service freddie definite mu...,5
48,oBNrLz4EDhiscSlbOl8uAw,Ruby Slipper - New Orleans,rude,place rudest server think ever displeasure enc...,1,jerry,jerry jerry jerry\n\njerry took great care us ...,5
49,oBNrLz4EDhiscSlbOl8uAw,Ruby Slipper - New Orleans,manager,food service amazing totally worth wait \n\nm...,5,loved loved,omg loved loved place breakfast spot shrimp gr...,5

In [8]:
df_example.rename(columns={'clean_text': 'complaint_sample_reviews'}, inplace=True)

In [14]:
df_example

,business_id,name,complaint_words,complaint_sample_reviews,complaint_stars,praise_words,praise_sample_reviews,praise_stars
0,GBTPC53ZrG1ZBY3DT8Mbcw,Luke,poor,let start saying oysters wonderful rest meal ...,2,best oyster,went happy hour raw oysters heaven perfectio...,5
1,GBTPC53ZrG1ZBY3DT8Mbcw,Luke,customers,travel quite bit let say amazing customer serv...,5,savannah,suffering luke withdrawal since last trip jazz...,5
2,GBTPC53ZrG1ZBY3DT8Mbcw,Luke,terrible,place sucks terrible service overpriced medioc...,1,sprouts amazing,reservations two seated right away within two...,2
3,GBTPC53ZrG1ZBY3DT8Mbcw,Luke,second,second choice finding rio mar closed mardi gra...,5,richie rich,restaurant star food service went bachelorett...,5
4,GBTPC53ZrG1ZBY3DT8Mbcw,Luke,open,place hip perhaps hip many tolerate boistero...,4,tristan,stumbled upon lukes way alabama via nola firs...,4
5,qb28j-FNX1_6xm7u372TZA,Gumbo Shop,mushy,thing worth chicken andouille gumbo family mem...,2,tim,first restaurant ever went first visit nola s...,5
6,qb28j-FNX1_6xm7u372TZA,Gumbo Shop,frozen,awful simply awful completely embarrassed poor...,1,everyday,bread pudding come get bread pudding probabl...,5
7,qb28j-FNX1_6xm7u372TZA,Gumbo Shop,waste,came highly recommended close friend come arou...,1,soooooo,everyday nola multiple occasions even bought c...,5
8,qb28j-FNX1_6xm7u372TZA,Gumbo Shop,awful,awful simply awful completely embarrassed poor...,1,boudin creole,little lot things chicken okra gumbo louisiana...,5
9,qb28j-FNX1_6xm7u372TZA,Gumbo Shop,trap,tourist trap yes give stars atmosphere food...,2,boudin creole mustard,little lot things chicken okra gumbo louisiana...,5
10,_C7QiQQc47AOEv4PE3Kong,Commander's Palace,shorts,yes want eat here\nif want great old southern ...,5,years come,service impeccable food talking years come fav...,5
11,_C7QiQQc47AOEv4PE3Kong,Commander's Palace,wearing,great service well done food little hyped uppr...,4,place especially,whenever travel received suggestions friends c...,5
12,_C7QiQQc47AOEv4PE3Kong,Commander's Palace,rude,would give place quite somewhat better ive ...,4,fourth,always wanted visit commanders palace finally...,5
13,_C7QiQQc47AOEv4PE3Kong,Commander's Palace,terrible,start saying food amazing desserts bwst part ...,3,amazing service impeccable,came large group party food amazing service im...,5
14,_C7QiQQc47AOEv4PE3Kong,Commander's Palace,dressed,second visit commanders palace enjoy dining re...,5,orleans one best,commanders palace largely considered best rest...,5
15,VQcCL9PiNL_wkGf-uF3fjg,Royal House,disgusting,disgusting food came cold shrimps still poop v...,1,best servers,chose place anniversary dinner boyfriend sunda...,5
16,VQcCL9PiNL_wkGf-uF3fjg,Royal House,burnt,royal house nice hidden gem new orleans aptly ...,4,melva server,service melva server bubbly sweet loves job kn...,5
17,VQcCL9PiNL_wkGf-uF3fjg,Royal House,worst service,restaurant worst service restaurant ever nola ...,1,dream,came due fellow yelpers wanted try alligator n...,4
18,VQcCL9PiNL_wkGf-uF3fjg,Royal House,time money,first arrive get seated balcony everything le...,1,importantly,one word becks best bartender ever know alcoho...,5
19,VQcCL9PiNL_wkGf-uF3fjg,Royal House,service horrible,used love restaurant got new chef everything c...,1,leroy,came large group around saturday seated immed...,5
20,VaO-VW3e1kARkU9bP1E7Fw,Felix's Restaurant & Oyster Bar,disgusting,im giving stars oysters plump pretty good sa...,2,yvette,ended felixs meeting locals asking oyster reco...,5
21,VaO-VW3e1kARkU9bP1E7Fw,Felix's Restaurant & Oyster Bar,awful,awful overpriced food jambalaya resembled uncl...,1,way better acme,one best meals ive new orleans way better acme...,5
22,VaO-VW3e1kARkU9bP1E7Fw,Felix's Restaurant & Oyster Bar,bill,consistently great service great food never wa...,5,get charbroiled,ever new orleans must go felixs best oysters i...,5
23,VaO-VW3e1kARkU9bP1E7Fw,Felix's Restaurant & Oyster Bar,dirty,kind divey spot food oysters ok kind dirty gue...,2,sat oyster,best oyster new orleans husband sat oyster bar...,5
24,VaO-VW3e1kARkU9bP1E7Fw,Felix's Restaurant & Oyster Bar,empty,sit bar want quicker service \n\nthey pretty ...,3,wait line across,great food great service great location grill...,5
25,6a4gLLFSgr-Q6CZXDLzBGQ,Cochon,terrible,great food terrible service get seated rese...,3,rocks,place rocks asked concierge westin best local...,5
26,6a4gLLFSgr-Q6CZXDLzBGQ,Cochon,worst,nochon hype substance first service sucks gi...,1,oysters die,awesome fantastic staff great atmosphere crawf...,5
27,6a4gLLFSgr-Q6CZXDLzBGQ,Cochon,hostess,sis fabulous dinner cochon wow started w fri...,5,amazing mac,omg begin food amazing mac cheese alligator gu...,5
28,6a4gLLFSgr-Q6CZXDLzBGQ,Cochon,salty,get people come food salty uninspired servers ...,1,go nola,absolutely delicious alligator amazing even th...,5
29,6a4gLLFSgr-Q6CZXDLzBGQ,Cochon,rude,get people come food salty uninspired servers ...,1,amazing oysters,amazing oysters crocodile delicious broccoli s...,5
30,iSRTaT9WngzB8JJ2YKJUig,Mother's Restaurant,place dirty,place dirty rude flavor cold food disappoi...,1,boy delicious,waited line outside lunch glad someone told us...,5
31,iSRTaT9WngzB8JJ2YKJUig,Mother's Restaurant,rude service,absolutely trash avoid place \n rude service\n...,1,best poboy,incredible food ferdi special best poboy new o...,5
32,iSRTaT9WngzB8JJ2YKJUig,Mother's Restaurant,filthy,hear place always long line people even waitin...,1,fried chicken worth,based recommendation friend looking forward tr...,3
33,iSRTaT9WngzB8JJ2YKJUig,Mother's Restaurant,disgusting,place dirty rude flavor cold food disappoi...,1,chicken worth,based recommendation friend looking forward tr...,3
34,iSRTaT9WngzB8JJ2YKJUig,Mother's Restaurant,worse,chifoodie nolatourism foodtourism blackownedbu...,2,authentic cajun,im sitting mardi gras weekend new orleans no...,4
35,ac1AeYqs8Z4_e2X5M3if2A,Oceana Grill,poisoning,worst meal ive ever served anywhere ever\n\ni ...,1,service errol,nola days ate breakfast twice service errol ...,5
36,ac1AeYqs8Z4_e2X5M3if2A,Oceana Grill,disgusting,food hear okay seafood came bit warm sitting h...,3,amazing new orleans,oh goodness even know start incredible restaur...,5
37,ac1AeYqs8Z4_e2X5M3if2A,Oceana Grill,food poisoning,worst meal ive ever served anywhere ever\n\ni ...,1,amazing new,oh goodness even know start incredible restaur...,5
38,ac1AeYqs8Z4_e2X5M3if2A,Oceana Grill,sick,friend new orleans days went twice thats good...,5,best waiter,first night ran mardi gras parade krewe du vie...,4
39,ac1AeYqs8Z4_e2X5M3if2A,Oceana Grill,nightmares,finally decided write review watching episode ...,4,omg good,yesterday marks rd time dine times amazing se...,5
40,_ab50qdWOk0DdB6XOrBitw,Acme Oyster House,waste,yes acme charbroiled oysters came table bubbl...,2,line scare,new orleans week eat every day many times alwa...,5
41,_ab50qdWOk0DdB6XOrBitw,Acme Oyster House,poor,many acme locations many occasions sampled muc...,5,orleans oyster,food good restaurant visit every time im new o...,5
42,_ab50qdWOk0DdB6XOrBitw,Acme Oyster House,manager,party po boy served cent bread chargrilled ...,1,new orleans oyster,food good restaurant visit every time im new o...,5
43,_ab50qdWOk0DdB6XOrBitw,Acme Oyster House,horrible,place good ok oysters good place town real con...,2,changed life,absolutely amazing food boo fries changed life,5
44,_ab50qdWOk0DdB6XOrBitw,Acme Oyster House,business,trips nola past months ive managed eat acme o...,5,hands best oysters,hands best oysters ever charbroiled oysters se...,5
45,oBNrLz4EDhiscSlbOl8uAw,Ruby Slipper - New Orleans,terrible,came rainy saturday morning breakfast group g...,4,server freddie awesome,awesome eggs benedict bloody marys fast friend...,5
46,oBNrLz4EDhiscSlbOl8uAw,Ruby Slipper - New Orleans,horrible,hopping loud bustling joint late saturday morn...,4,freddie great server,food great easily accommodated group try corn...,5
47,oBNrLz4EDhiscSlbOl8uAw,Ruby Slipper - New Orleans,worst,sucks worst biscuits ever extremely pricey poo...,1,service freddie,great food awesome service freddie definite mu...,5
48,oBNrLz4EDhiscSlbOl8uAw,Ruby Slipper - New Orleans,rude,place rudest server think ever displeasure enc...,1,jerry,jerry jerry jerry\n\njerry took great care us ...,5
49,oBNrLz4EDhiscSlbOl8uAw,Ruby Slipper - New Orleans,manager,food service amazing totally worth wait \n\nm...,5,loved loved,omg loved loved place breakfast spot shrimp gr...,5

In [15]:
df_example.to_csv('csv/df_example_top10.csv', index=False)

In [4]:
pd.read_csv('csv/df_example_top10.csv')

,business_id,name,complaint_words,complaint_sample_reviews,complaint_stars,praise_words,praise_sample_reviews,praise_stars
0,GBTPC53ZrG1ZBY3DT8Mbcw,Luke,poor,"Wanted to eat here, tried to eat here, reserva...",1,best oyster,We went here for the happy hour raw oysters. ...,5
1,GBTPC53ZrG1ZBY3DT8Mbcw,Luke,customers,I have been to LUKE four times and this was my...,1,savannah,Had been suffering from Luke withdrawal since ...,5
2,GBTPC53ZrG1ZBY3DT8Mbcw,Luke,terrible,this place SUCKS. Terrible service and overpri...,1,sprouts amazing,Amazing meal great service. It's not cheap but...,5
3,GBTPC53ZrG1ZBY3DT8Mbcw,Luke,second,this place SUCKS. Terrible service and overpri...,1,richie rich,This restaurant is 5 star food and service. We...,5
4,GBTPC53ZrG1ZBY3DT8Mbcw,Luke,open,Are u kidding me? Not only were there 8 tables...,1,tristan,Our Waiter was Tristan who was so patient & he...,5
5,qb28j-FNX1_6xm7u372TZA,Gumbo Shop,mushy,Great crawfish corn chowder but the crawfish i...,1,tim,First restaurant I ever went to on my very fir...,5
6,qb28j-FNX1_6xm7u372TZA,Gumbo Shop,frozen,"Awful, simply awful. I was completely embarras...",1,everyday,Bread pudding. Don't come here and not get th...,5
7,qb28j-FNX1_6xm7u372TZA,Gumbo Shop,waste,Came here after it was highly recommended by a...,1,soooooo,Are there everyday I was in NOLA on multiple o...,5
8,qb28j-FNX1_6xm7u372TZA,Gumbo Shop,awful,"Awful, simply awful. I was completely embarras...",1,boudin creole,Had a little of a lot of things: chicken okra ...,5
9,qb28j-FNX1_6xm7u372TZA,Gumbo Shop,trap,Some of the saddest worst gumbo I've ever had....,1,boudin creole mustard,Had a little of a lot of things: chicken okra ...,5
10,_C7QiQQc47AOEv4PE3Kong,Commander's Palace,shorts,"No shorts! What's up with that, really? We wer...",1,years come,"The service is impeccable, the food will have ...",5
11,_C7QiQQc47AOEv4PE3Kong,Commander's Palace,wearing,"This place was on my wife's bucket list, so o...",1,place especially,"As I do whenever I travel, I received suggesti...",5
12,_C7QiQQc47AOEv4PE3Kong,Commander's Palace,rude,I was very excited to try this famous restaura...,1,fourth,I had always wanted to visit the Commander's P...,5
13,_C7QiQQc47AOEv4PE3Kong,Commander's Palace,terrible,The food was good here but I swear we are neve...,1,amazing service impeccable,Came here for a large group party and the food...,5
14,_C7QiQQc47AOEv4PE3Kong,Commander's Palace,dressed,"The food was okay -- but not worth the price, ...",1,orleans one best,Commander's Palace is largely considered the b...,5
15,VQcCL9PiNL_wkGf-uF3fjg,Royal House,disgusting,Disgusting. The food came out cold. The shrimp...,1,best servers,Chose this place for an anniversary dinner wit...,5
16,VQcCL9PiNL_wkGf-uF3fjg,Royal House,burnt,Had high hopes for this place based on the rev...,1,melva server,Service: MELVA was our server. She was on it. ...,5
17,VQcCL9PiNL_wkGf-uF3fjg,Royal House,worst service,This restaurant has the worst service of any r...,1,dream,I dream about those grilled oysters. Definitel...,5
18,VQcCL9PiNL_wkGf-uF3fjg,Royal House,time money,First we arrive and get seated on the balcony....,1,importantly,I have one word... BECKS. She is the best bart...,5
19,VQcCL9PiNL_wkGf-uF3fjg,Royal House,service horrible,I used to love this restaurant but they got a ...,1,leroy,Came here with a large group around 5:30 on a ...,5
20,VaO-VW3e1kARkU9bP1E7Fw,Felix's Restaurant & Oyster Bar,disgusting,Hostess was rude to absolutely everyone in lin...,1,yvette,Ended up at Felix's after meeting a few locals...,5
21,VaO-VW3e1kARkU9bP1E7Fw,Felix's Restaurant & Oyster Bar,awful,"Awful, overpriced food. Our Jambalaya resemble...",1,way better acme,One of the best meals I've had in New Orleans....,5
22,VaO-VW3e1kARkU9bP1E7Fw,Felix's Restaurant & Oyster Bar,bill,Oysters were good but no different than the ot...,1,get charbroiled,"If you are ever in New Orleans, you MUST go to...",5
23,VaO-VW3e1kARkU9bP1E7Fw,Felix's Restaurant & Oyster Bar,dirty,I would come here years ago. Thought I would c...,1,sat oyster,They had the best oyster in a of new orleans! ...,5
24,VaO-VW3e1kARkU9bP1E7Fw,Felix's Restaurant & Oyster Bar,empty,Holy cow... what a terrible disappointment! On...,1,wait line across,"Great food, great service, great location. Th...",5
25,6a4gLLFSgr-Q6CZXDLzBGQ,Cochon,terrible,"Food is good, the service is just terrible. W...",1,rocks,This place rocks. I asked the concierge at th...,5
26,6a4gLLFSgr-Q6CZXDLzBGQ,Cochon,worst,NO-CHON. All hype no substance. First of all ...,1,oysters die,Awesome! Fantastic staff. Great atmosphere. Cr...,5
27,6a4gLLFSgr-Q6CZXDLzBGQ,Cochon,hostess,We were told it would be a 45 min to an hour w...,1,amazing mac,OMG where do I begin!! The food was amazing!! ...,5
28,6a4gLLFSgr-Q6CZXDLzBGQ,Cochon,salty,I don't get why people come here. The food is ...,1,go nola,Absolutely delicious!!! The alligator was amaz...,5
29,6a4gLLFSgr-Q6CZXDLzBGQ,Cochon,rude,I don't get why people come here. The food is ...,1,amazing oysters,Amazing. Had the oysters and crocodile- delici...,5
30,iSRTaT9WngzB8JJ2YKJUig,Mother's Restaurant,place dirty,"This place was dirty, rude, no flavor, and ...",1,boy delicious,Waited in line outside for lunch. So glad some...,5
31,iSRTaT9WngzB8JJ2YKJUig,Mother's Restaurant,rude service,Absolutely trash! Avoid this place! \n1. Rude ...,1,best poboy,"Incredible food! I had the Ferdi Special, whic...",5
32,iSRTaT9WngzB8JJ2YKJUig,Mother's Restaurant,filthy,So... I hear this place always has a long line...,1,fried chicken worth,The gumbo is WOW. The fried chicken is worth ...,5
33,iSRTaT9WngzB8JJ2YKJUig,Mother's Restaurant,disgusting,"This place was dirty, rude, no flavor, and ...",1,chicken worth,The gumbo is WOW. The fried chicken is worth ...,5
34,iSRTaT9WngzB8JJ2YKJUig,Mother's Restaurant,worse,This place blows...I think that it relies sole...,1,authentic cajun,"If you are looking for authentic cajun food, y...",5
35,ac1AeYqs8Z4_e2X5M3if2A,Oceana Grill,poisoning,"Worst meal I've ever been served, anywhere, ev...",1,service errol,We were only in Nola for 3 days and ate breakf...,5
36,ac1AeYqs8Z4_e2X5M3if2A,Oceana Grill,disgusting,GARBAGE FOOD. It's a prime location on a disgu...,1,amazing new orleans,Oh my goodness I don't even know where to star...,5
37,ac1AeYqs8Z4_e2X5M3if2A,Oceana Grill,food poisoning,"Worst meal I've ever been served, anywhere, ev...",1,amazing new,Oh my goodness I don't even know where to star...,5
38,ac1AeYqs8Z4_e2X5M3if2A,Oceana Grill,sick,"Worst meal I've ever been served, anywhere, ev...",1,best waiter,AMAZING courtyard and brunch. Food was delicio...,5
39,ac1AeYqs8Z4_e2X5M3if2A,Oceana Grill,nightmares,Had the chicken fettuccine Alfredo and fried s...,1,omg good,Yesterday marks my 3rd time to dine here. All ...,5
40,_ab50qdWOk0DdB6XOrBitw,Acme Oyster House,waste,A friend insisted we go here because it was ap...,1,line scare,Was in New Orleans for a week and eat here eve...,5
41,_ab50qdWOk0DdB6XOrBitw,Acme Oyster House,poor,"Ok, I've been to New Orleans several time year...",1,orleans oyster,The food was so good there. Its a restaurant t...,5
42,_ab50qdWOk0DdB6XOrBitw,Acme Oyster House,manager,We were a party of 6. The PO boy is served on ...,1,new orleans oyster,The food was so good there. Its a restaurant t...,5
43,_ab50qdWOk0DdB6XOrBitw,Acme Oyster House,horrible,got poisoned actually from their raw oysters! ...,1,changed life,Absolutely amazing food! The boo fries changed...,5
44,_ab50qdWOk0DdB6XOrBitw,Acme Oyster House,business,Manager did not want to accommodate our larger...,borderline rude. Lost my business forever.,hands best oysters,Hands down the best oysters that I have EVER h...,5
45,oBNrLz4EDhiscSlbOl8uAw,Ruby Slipper - New Orleans,terrible,Cockroaches and crappy bar service\n\nTo the t...,1,server freddie awesome,Awesome eggs Benedict and bloody Mary's. Fast ...,5
46,oBNrLz4EDhiscSlbOl8uAw,Ruby Slipper - New Orleans,horrible,The food is horrible! Bland and not original...,1,freddie great server,Food was great and they easily accommodated ou...,5
47,oBNrLz4EDhiscSlbOl8uAw,Ruby Slipper - New Orleans,worst,It sucks worst biscuits I ever had and extreme...,1,service freddie,"Great food, awesome service from Freddie. A de...",5
48,oBNrLz4EDhiscSlbOl8uAw,Ruby Slipper - New Orleans,rude,This place has the rudest server I think I hav...,1,jerry,JERRY JERRY JERRY!!!!!!!\n\nJerry took great c...,5
49,oBNrLz4EDhiscSlbOl8uAw,Ruby Slipper - New Orleans,manager,After making a reservation and being told to a...,1,loved loved,OMG!!! Loved Loved this place. The breakfast w...,5